test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>
 
# Use rails credentials:edit to set the AWS secrets (as aws:access_key_id|secret_access_key)

amazon_production:
  service: S3
  access_key_id: "AKIAJMBF5ZIQN2R5E37A"
  secret_access_key: "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"
  region: "us-east-2"
  bucket: "idosonaweb"


